services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=Blogging-API'
      - 'MYSQL_PASSWORD=blogAPI'
      - 'MYSQL_ROOT_PASSWORD=pass'
      - 'MYSQL_USER=pass'
    ports:
      - '3306:3306'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'